version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: UserAuthentication
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  foxtrend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      DB_URL: jdbc:mysql://db:3308/UserAuthentication
      MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
  mongo_data:
